---
abstract: A slice of method calls within an object
author:
  - 'Laurent Dami <dami@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Method-Slice
provides:
  Method::Slice:
    file: lib/Method/Slice.pm
    version: 0.01
requires:
  Want: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/damil/Method-Slice
version: 0.01
